### PR TITLE
Theming/kirby list

### PR DESCRIPTION
**Pull request by PetarRing**
Theming for list, -header and -item.

### CODE REVIEW

**Comment by jonasjensen-brolstark** [comment]
Am I wrong, or are these changes not included in PR #91 ?

**Comment by PetarRing** [comment]
> Am I wrong, or are these changes not included in PR #91 ?

They should be since this branch was merged onto that.

**Comment by jonasjensen-brolstark** [comment]
> > Am I wrong, or are these changes not included in PR #91 ?
> 
> They should be since this branch was merged onto that.

Should we not drop this PR then? Unless you want your name on the PR 😄

**Comment by PetarRing** [comment]
> > > Am I wrong, or are these changes not included in PR #91 ?
> > 
> > 
> > They should be since this branch was merged onto that.
> 
> Should we not drop this PR then? Unless you want your name on the PR 😄

Lets do that then 😄

**Pull request closed without merging**
