### PR TITLE
Fix font-size for ion-item in kirby-item

### LINKED ISSUE #1242: [Enhancement] Items in a list with a checkbox/radio should have a 16px font size
**Is your enhancement request related to a problem? Please describe.**
When rendered in a list the items with a checkbox/radio button inside of them will have a smaller font, see also: https://cookbook.kirby.design/home/showcase/checkbox
or the screenshot below: 
Skærmbillede 2021-01-15 kl  09 55 22

**Describe the solution you'd like**
When a item has a checkbox/radio inside of it the font should be 16px like shown in the screenshot below
Skærmbillede 2021-01-15 kl  09 57 13

**Describe alternatives you've considered**
Nothing more 

**Additional context**
Nothing more

### PR DESCRIPTION
**Pull request by thupi**
## Which issue does this PR close?

This PR closes #1242 

## What is the new behavior?

This removes the font-size applied to ion-item which causes the children of the component to default to the applied font-size 14px. By removing that style property it will default to the 16px.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Reminders
- [ ] ~~Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".~~
- [x] Make sure you have updated the cookbook with examples and showcases (for bug fixes, enhancements & new components).

### Review  
- [x] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review).
- [x] Request that the changes are code-reviewed 
- [ ] ~~Request that the changes are [UX reviewed](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#ux-review) (only necessary if your PR introduces visual changes)~~

When the pull request has been approved it will be merged to `develop` by Team Kirby.

### CODE REVIEW

**Review by mark-drastrup — DISMISSED** [review]

**Comment by mark-drastrup** [comment]
@thupi sorry I think I was too quick with the approval 😅 I just looked through the cookbook examples for the checkbox and when the checkbox is used in a list, then the font-size of the label becomes 17px now. This seems to be inherited from the ion-item that wraps the checkbox.

Screenshot 2022-11-10 at 17 03 01

**Comment by thupi** [comment]
@mark-drastrup I see, I spent too much time on making sure that it didn't impact all the other examples of list items that I forgot to verify the font-size for checkbox 😅 Instead of removing the style I changed to use the 16px size now :-) !

It should fix it, thanks for pointing it out 😃 !

**Comment by mark-drastrup** [comment]
@thupi haha it's also used in so many places, that it's hard to keep track of it all 😅 It looks perfect now! You're welcome! 😄

**Review by mark-drastrup — APPROVED** [review]

**Pull request merged**
