### PR TITLE
(performance): fix memory leak in BaseChartComponent

### PR DESCRIPTION
**Pull request by kievsash**
## Which issue does this PR close?
# Scenario Description

**Scenario**

* open the flow app at the root page: `http://localhost:4200/` (lets name it room page /)
* navigate to `/transaction-details-flow/for-you` by pressing the second card with the title **'Navigate to List Item detail'**
* navigate back to the room page page by pressing the (<) back button

## *Remark
Ionic tends to keep its views in memory in order to reuse them at a later point in time.
In order to properly track memory leaks, we consider the initial state after the **first scenario run**. Leaks are treated as memory usage increase ***after*** first iterations (second, third, etc).

## Summary (TL,DR)
When repeating the scenario, the number of DOM elements and JS heap-size increases. **We can observe memory leaks**

# Current State (before fix)
## Memory Footprint
The following table shows the memory footprint of the application performing
the scenario.

| Metric  | Chrome Tab | JS Heap Size | DOM Nodes | JS Event Listeners |
|---------|------------|--------------|-----------|--------------------|
| Initial | `95.6MB`   | `19.6MB`     | `115`     | `20`               |
| 1 Rep.  | `96MB`     | `22MB`       | `414`     | `58`               |
| 2 Rep.  | `˜96.5MB`  | `22.5MB`     | `685`     | `69`               |
| 3 Rep.  | `˜97MB`    | `23.1MB`     | `956`     | `80`               |
| 4 Rep.  | `97.8MB`   | `23.6MB`     | `1227`    | `91`               |

## Performance monitor

The Performance Observer nicely visualizes that the memory increases after each repetition.
(especially obvious for detached elements and JS event listeners)
performance-audit-before

## Detached Elements

detached-elements-before

The `detached elements` analysis also indicates memory leaks as the amount of detached elements is increasing from 4 to 16 after 4 repititions.

It looks like the `BaseChartComponent` is the candidate not releasing its references.

# Fixed State
As a result of investigation it was revealed that the `BaseChartComponent` does not destroy previously created charts after it gets destroyed.
As a fix we implemented the `ngOnDestroy` method and call `chartJSService.destroyChart()`.

## Memory Footprint

| Metric  | Chrome Tab | JS Heap Size | DOM Nodes | JS Event Listeners |
|---------|------------|--------------|-----------|--------------------|
| Initial | `97.9MB`   | `20.6MB`     | `115`     | `20`               |
| 1 Rep.  | `101MB`    | `23.2MB`     | `414`     | `52`               |
| 2 Rep.  | `101MB`    | `23.7MB`     | `414`     | `52`               |
| 3 Rep.  | `108MB`    | `24.5MB`     | `429`     | `52`               |
| 4 Rep.  | `108MB`    | `24.3MB`     | `429`    | `52`               |
| 6 Rep.  | `106MB`    | `24.3MB`     | `429`    | `52`               |

As we can see the number of DOM nodes and JS Event Listeners stays stable. 
There are some fluctuations of JS heap size but without any stable increase.

## Performance monitor

performance-audit-after

The performance monitor now clearly shows how the memory is getting released after each iteration of the analysed scenario.
(except first one, but it is ionic behavior)

## Detached elements

detached-elements-after

Also the number of detached elements stays stable when repeating the scenario multiple times.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Reminders
- [x] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Make sure you have updated the cookbook with examples and showcases (for bug fixes, enhancements & new components).

### Review  
- [ ] Determine if your changes are a fix, feature or breaking-change, and add the matching label to your PR. If it is tooling, dependency updates or similar, add ignore-for-release.
- [x] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review).
- [x] Request that the changes are code-reviewed 
- [ ] Request that the changes are [UX reviewed](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#ux-review) (only necessary if your PR introduces visual changes)

When the pull request has been approved it will be merged to `develop` by Team Kirby.

### CODE REVIEW

**Review by RasmusKjeldgaard — APPROVED** [review]
Great finding, thank you very much for your contribution!

**Comment by RasmusKjeldgaard** [comment]
@kievsash could you sync the branch so we can merge?

**Comment by kievsash** [comment]
Hey @RasmusKjeldgaard 
Pressed "merge develop" button but looks like some approval needed

**Comment by RasmusKjeldgaard** [comment]
> Pressed "merge develop" button but looks like some approval needed

Thanks, I will have to look into making our Github setup more fork-friendly.

**Pull request merged**
