### PR TITLE
Make back buttons on Page bigger

### PR DESCRIPTION
**Pull request by MortenGregersen**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] cookbook application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Right now the back buttons are 24x32 px, because of the lack of texts in them. This is a bit too small to hit on device. Apple recommends buttons to be at least 44 px on one of the sides, for them to be hittable.

Issue Number: N/A

## What is the new behavior?

With this change, the buttons will be 44x44 px, and thereby easier easier to hit. It is possible to set a `--min-width` on the back button, but it centers the icon (not preferred), so we need to use the `--padding-end`. This creates an empty space that the title can fill out (may be a problem).

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by bommariusser** [comment]
@MortenGregersen this task is pretty much related to ur task or? https://github.com/kirbydesign/designsystem/issues/866

The back button, is that a kirby button? 
Is the back button the same as the buttons on the right side of the toolbar? 

:)

**Comment by MortenGregersen** [comment]
It is related. Didn’t see that issue. 

It is the button on the left side of the page title when the user can navigate back.

**Comment by bommariusser** [comment]
but its also related to the other buttons in the toolbar? :) ill look at it tomorrow. excited much!

**Comment by MortenGregersen** [comment]
After talking with @bommariusser, I have now made the back button 44x44 px.

I haven't touched the other buttons. I think this should be done separately, as the buttons are given by the consuming app.

**Pull request merged**
