### PR TITLE
Fix setting disclosure input to null in kirby-item

### LINKED ISSUE #2905: [BUG] Conditionally set disclosure on kirby-item
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
 
It is not possible to conditionally set the disclosure of a `kirby-item` element, as the type of `disclosure` does not permit this.

## Describe how to reproduce the bug

Use either of the following patterns to conditionally define the disclosure:

```html
<kirby-item [disclosure]="someCondition ? 'arrow-more' : undefined">
  <h3>Item label 1</h3>
</kirby-item>
<kirby-item [disclosure]="someCondition ? 'arrow-more' : null">
    <h3>Item label 2</h3>
</kirby-item>
```

## Which Kirby version was used?
 
v8.0.1

## What was the expected behavior?

The program compiles without errors

## Add any screenshots

image

## Please complete the following information:
- OS: MacOS (BD dev machine).
- Browser: N/A
- Browser version: N/A

## Are there any additional context?

It may be as simple as extending the type of `disclosure` to include either `null`, `undefined`, or `'none'`.

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [x] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/main/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [x] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

### PR DESCRIPTION
**Pull request by bdyhsj**
## Which issue does this PR close?

This PR closes #2905 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No 

## Are there any additional context?
It has been tested to work by modifying the showcase example.
This modification has not been added to the PR as it is a very minor change.

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Reminders
- [x] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [x] Make sure you have updated the cookbook with examples and showcases (for bug fixes, enhancements & new components).

### Review  
- [x] Determine if your changes are a fix, feature or breaking-change, and add the matching label to your PR. If it is tooling, dependency updates or similar, add ignore-for-release.
- [x] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review).
- [x] Request that the changes are code-reviewed 
- [ ] Request that the changes are [UX reviewed](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#ux-review) (only necessary if your PR introduces visual changes)

When the pull request has been approved it will be merged to `develop` by Team Kirby.

### CODE REVIEW

**Comment by RasmusKjeldgaard** [comment]
Remember to add it to the API table too!

**Comment by bdyhsj** [comment]
Should i include a test to verify that the disclosure is removed correctly after setting to null?

**Comment by RasmusKjeldgaard** [comment]
> Should i include a test to verify that the disclosure is removed correctly after setting to null?

Good idea, would be a nice addition to ensure that e.g. the fallback icon for kirby-icon is not shown if null is supplied.

**Review by RasmusKjeldgaard — APPROVED** [review]
🎉

**Pull request merged**
