### PR TITLE
Enable click on selected item in Segmented Control

### LINKED ISSUE #1744: [BUG] Wrong Spacing in segmented control
- [ ] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

1. Go tohttps://cookbook.kirby.design/home/showcase/segmented-control
2. See error -->

Skærmbillede 2021-09-10 kl  09 55 09

## Which Kirby version was used?
v3.0.10 (8 Sep 2021)

## What was the expected behavior?
There shouldnt be any white overflow behind the black "button"

## Please complete the following information:
- iOS & Chrome

## Are there any additional context?
I havent tried on Android but i guess its the same issue
<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](../CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](../SUPPORT.md/#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](../CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [master branch](https://github.com/kirbydesign/designsystem/tree/master) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

### LINKED ISSUE #2265: [BUG] Segmented Control - Enable click on selected item
In default mode you should be able to interact with the selected item, e.g. by clicking. Hover and active states should be applied.

Similar to chip mode.

### Default mode

https://user-images.githubusercontent.com/150451/168811017-4a926e0b-e172-4d79-a5db-8877c73847e6.mov

### Chip mode

https://user-images.githubusercontent.com/150451/168811041-8a9c4de4-2afd-4d1f-95b4-b05886ebecbc.mov

### PR DESCRIPTION
**Pull request by RasmusKjeldgaard**
## Which issue does this PR close?

This PR closes #2265 closes #1744

## What is the new behavior?
Segmented Control now gets the correct state for hover and active when interacting with an already selected segment. 

This includes a small refactor to get rid of the wrapper element around each segment-button in the Segmented Control template, as this was the culprit for not being able to interact with the underlying segment. This `div` wrapper element with `position: relative` was originally introduced to be able to place a badge via `top/left/right` css properties, but is now removed in favor of an `ng-container` that will not clutter the DOM. 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Reminders
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Make sure you have updated the cookbook with examples and showcases (for bug fixes, enhancements & new components).

### Review  
- [x] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review).
- [x] Request that the changes are code-reviewed 
- [x] Request that the changes are [UX reviewed](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#ux-review) (only necessary if your PR introduces visual changes)

When the pull request has been approved it will be merged to `develop` by Team Kirby.

### CODE REVIEW

**Review by jkaltoft — COMMENTED** [review]
### Suggestion

Wrap `<kirby-badge>` in a container that creates a `position: relative` context for it: 

```html
<ng-container *ngFor="let item of items">
  <ion-segment-button [value]="item.id">{{ item.text }} </ion-segment-button>
  <div class="segment-btn-wrapper">
    <kirby-badge
      *ngIf="item.badge"
      role="text"
      [attr.aria-label]="item.badge.description"
      [themeColor]="item.badge.themeColor"
    >
      <ng-container *ngIf="item.badge.icon; else badgeContent">
        <kirby-icon
          *ngIf="item.badge.isCustomIcon; else defaultIconName"
          [customName]="item.badge.icon"
        ></kirby-icon>
        <ng-template #defaultIconName>
          <kirby-icon [name]="item.badge.icon"></kirby-icon>
        </ng-template>
      </ng-container>
      <ng-template #badgeContent>
        {{ item.badge.content }}
      </ng-template>
    </kirby-badge>
  </div>
</ng-container>
```

I think you can reduce/simplify what needs to be changed - in particular you can avoid the `width: 0;` declaration on `kirby-badge`. I would choose another classname than `segment-btn-wrapper` but you get the point 🙂

**Comment by RasmusKjeldgaard** [comment]
> [...]
> I think you can reduce/simplify what needs to be changed - in particular you can avoid the `width: 0;` declaration on `kirby-badge`. I would choose another classname than `segment-btn-wrapper` but you get the point 🙂

The reason for `width: 0` is that I want the badge element to participate in the ordinary flow of the document, but ideally not take up any width in the segmented control. This way I can easily position the badge relatively to the segment-button before it.

Would this new container not still affect the total width of the segmented control?

**Comment by jkaltoft** [comment]
> Would this new container not still affect the total width of the segmented control?

No, due to its' content being removed from normal flow by using absolute positioning, the container will collapse and have an intrinsic width of 0.

**Review by jkaltoft — APPROVED** [review]
giphub

**Pull request merged**
