### PR TITLE
Changed DateInputDirective declaration

### LINKED ISSUE #3007: [BUG] `DateInputDirective` not declared in `FormFieldModule`
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
The `DateInputDirective` is not declared in `FormFieldModule`. This results in the styling being wrong.
## Describe how to reproduce the bug
Input this code. 
``` html
<kirby-form-field label="Date input" >
  <input kirby-input type="date" [size]="size" />
</kirby-form-field>
```

In the module import the following:
`FormFieldModule`

The issue can also be reproduced here: https://stackblitz.com/edit/angular-gii9b7?file=src/kirby-demo/kirby-demo.module.ts 
## Which Kirby version was used?
8.3.1

## What was the expected behavior?
The date input shouldn't have a calendar icon.
Screenshot 2023-04-21 at 13 19 09

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [x] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/main/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

### PR DESCRIPTION
**Pull request by kodeaben**
## Which issue does this PR close?

This PR closes #3007

## What is the new behavior?
`DateInputDirective` is now applied through the `hostDirectives` component decorator prop on `InputComponent` and updated with guards to prevent executing it's masking on non-date inputs.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Reminders
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Make sure you have updated the cookbook with examples and showcases (for bug fixes, enhancements & new components).

### Review  
- [ ] Determine if your changes are a fix, feature or breaking-change, and add the matching label to your PR. If it is tooling, dependency updates or similar, add ignore-for-release.
- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review).
- [ ] Request that the changes are code-reviewed 
- [ ] Request that the changes are [UX reviewed](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#ux-review) (only necessary if your PR introduces visual changes)

When the pull request has been approved it will be merged to `develop` by Team Kirby.

### CODE REVIEW

**Review by mark-drastrup — DISMISSED** [review]
Nice work!

**Review by jakobe — CHANGES_REQUESTED** [review]
As far as I can see the proper way to go about this, is to import the `DateInputDirective` into the `InputComponent` and leave this as standalone.
The directive only applies to Kirby date inputs, as per it's selector: `selector: '[kirby-input][type="date"]'`

**Comment by kodeaben** [comment]
> As far as I can see the proper way to go about this, is to import the `DateInputDirective` into the `InputComponent` and leave this as standalone. The directive only applies to Kirby date inputs, as per it's selector: `selector: '[kirby-input][type="date"]'`

I like your suggestion :) 

If I understand it correctly, you suggest the following: 

``` typescript
@Directive({
  standalone: true,
  selector: '[kirby-input][type="date"]',
})
export class DateInputDirective {}
```

``` typescript

@Component({
  standalone: true,
  imports: [CommonModule, DateInputDirective],
  ...
})
export class InputComponent {}
```

``` typescript
@NgModule({
  imports: [CommonModule, DecimalMaskDirective, InputComponent],
  declarations: [...declarations],
  exports: [...declarations, DecimalMaskDirective, InputComponent],
})
export class FormFieldModule {}
```

I fiddled around with it and I believe the issue with this implementation is that we are not exporting `DateInputComponent` from `FormFieldModule` which result in this error: 
Screenshot 2023-04-26 at 21 04 05

We can do the imports/exports of `DateInpoutDirective` in `FormFieldModule`, but I don't se any gains in such an implementation.

**Comment by jakobe** [comment]
> > As far as I can see the proper way to go about this, is to import the `DateInputDirective` into the `InputComponent` and leave this as standalone. The directive only applies to Kirby date inputs, as per it's selector: `selector: '[kirby-input][type="date"]'`
> 
> I like your suggestion :)
> 
> If I understand it correctly, you suggest the following:
> 
> ```ts
> @Directive({
>   standalone: true,
>   selector: '[kirby-input][type="date"]',
> })
> export class DateInputDirective {}
> ```
> 
> ```ts
> @Component({
>   standalone: true,
>   imports: [CommonModule, DateInputDirective],
>   ...
> })
> export class InputComponent {}
> ```
> 
> ```ts
> @NgModule({
>   imports: [CommonModule, DecimalMaskDirective, InputComponent],
>   declarations: [...declarations],
>   exports: [...declarations, DecimalMaskDirective, InputComponent],
> })
> export class FormFieldModule {}
> ```
> 
> I fiddled around with it and I believe the issue with this implementation is that we are not exporting `DateInputComponent` from `FormFieldModule` which result in this error: Screenshot 2023-04-26 at 21 04 05
> 
> We can do the imports/exports of `DateInpoutDirective` in `FormFieldModule`, but I don't se any gains in such an implementation.

Yes and no :)

The first part of exposing DateInputDirective by importing it in InputComponent is correct, but the part about FormFieldModule I don't get? InputCompont is already madea standalone component, why do you wan't to expose it through FormFieldModule? It might make sense, but it's a refactoring of the public API that isn't part of solving the issue at hand...

**Review by RasmusKjeldgaard — APPROVED** [review]
Looks good!

Consider removing [the cookbook notice](https://github.com/kirbydesign/designsystem/pull/3019/files) from this separate unmerged PR in this PR instead as the changes are related and solves the issue mentioned

**Review by jakobe — APPROVED** [review]

**Pull request merged**
